# Generated by Django 4.2.7 on 2025-11-20 23:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_carte', models.CharField(choices=[('jeune', 'Carte Jeune'), ('senior', 'Carte Senior'), ('famille', 'Carte Famille'), ('weekend', 'Carte Weekend')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('reduction_pourcentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carte de réduction',
                'verbose_name_plural': 'Cartes de réduction',
            },
        ),
        migrations.CreateModel(
            name='CarteReductionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=50)),
                ('date_expiration', models.DateField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.cartereduction')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_reduction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carte de réduction utilisateur',
                'verbose_name_plural': 'Cartes de réduction utilisateurs',
                'unique_together': {('utilisateur', 'numero_carte')},
            },
        ),
        migrations.CreateModel(
            name='Gare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('adresse', models.TextField()),
            ],
            options={
                'verbose_name': 'Gare',
                'verbose_name_plural': 'Gares',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='OffrePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reduction_pourcentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offres/')),
            ],
            options={
                'verbose_name': 'Offre promotion',
                'verbose_name_plural': 'Offres promotions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
                ('duree', models.DurationField()),
                ('classe', models.CharField(choices=[('1', 'Première classe'), ('2', 'Deuxième classe')], default='2', max_length=1)),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('places_disponibles', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('gare_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_arrivee', to='reservations.gare')),
                ('gare_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains_depart', to='reservations.gare')),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'ordering': ['heure_depart'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voyage', models.DateField()),
                ('nombre_places', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reduction_appliquee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('utilisee', 'Utilisée')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('carte', 'Carte bancaire'), ('paypal', 'PayPal'), ('cheque', 'Chèque')], max_length=20, null=True)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('code_reservation', models.CharField(max_length=20, unique=True)),
                ('carte_reduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.cartereductionutilisateur')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.train')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagers', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Passager',
                'verbose_name_plural': 'Passagers',
            },
        ),
    ]
