# Generated by Django 4.2.7 on 2025-11-25 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='planifie', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='reservations.train')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RetardTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voyage', models.DateField()),
                ('minutes_retard', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En cours de résolution'), ('resolu', 'Résolu')], default='signale', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='reservations.train')),
            ],
            options={
                'verbose_name': 'Retard',
                'verbose_name_plural': 'Retards',
                'ordering': ['-date_voyage', '-cree_le'],
                'unique_together': {('train', 'date_voyage')},
            },
        ),
    ]
