# Generated by Django 4.2.7 on 2025-11-25 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_maintenancetrain_retardtrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='nombre_voitures',
            field=models.IntegerField(default=8, help_text='Nombre de voitures dans le train', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
