# Generated by Django 4.2.7 on 2025-11-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_train_nombre_voitures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArretIntermediaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(help_text='Ordre de passage dans le trajet (1 = première gare après le départ)')),
                ('heure_passage', models.TimeField(blank=True, help_text='Heure de passage à cette gare', null=True)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets_intermediaires', to='reservations.gare')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets_intermediaires', to='reservations.train')),
            ],
            options={
                'verbose_name': 'Arrêt intermédiaire',
                'verbose_name_plural': 'Arrêts intermédiaires',
                'ordering': ['train', 'ordre'],
                'unique_together': {('train', 'ordre')},
            },
        ),
    ]
